[tool.black]
line-length = 120

[tool.poetry]
name = "tooling-project-assets"
version = "0.0.0"
description = ""
authors = ["Arduino <info@arduino.cc>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
yamllint = "^v1.26.2"
codespell = "^2.1.0"
black = "^21.7b0"
flake8 = "^3.9.2"
pep8-naming = "^0.12.0"
pytest = "^6.2.4"
GitPython = "^3.1.20"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
