[tool.black]
line-length = 120

[tool.poetry]
name = "tooling-project-assets"
version = "0.0.0"
description = ""
authors = ["Arduino <info@arduino.cc>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
yamllint = "^v1.27.1"
codespell = "^2.1.0"
black = "^22.6"
flake8 = "^4.0.1"
pep8-naming = "^0.13.0"
pytest = "^7.1.2"
GitPython = "^3.1.27"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
