# Source:
# https://github.com/arduino/tooling-project-assets/blob/main/issue-templates/template-choosers/general/config.yml
# See:
# https://docs.github.com/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser

contact_links:
  - name: Learn about using this project
    # TODO: Replace TODO_REPO_OWNER/TODO_REPO_NAME with the repository owner and name
    url: https://github.com/TODO_REPO_OWNER/TODO_REPO_NAME#readme
    about: Detailed usage documentation is available here.
  - name: Support request
    url: https://forum.arduino.cc/
    about: We can help you out on the Arduino Forum!
  - name: Issue report guide
    # TODO: Replace TODO_REPO_OWNER/TODO_REPO_NAME with the repository owner and name
    url: https://github.com/TODO_REPO_OWNER/TODO_REPO_NAME/blob/main/docs/contributor-guide/issues.md#issue-report-guide
    about: Learn about submitting issue reports to this repository.
  - name: Contributor guide
    # TODO: Replace TODO_REPO_OWNER/TODO_REPO_NAME with the repository owner and name
    url: https://github.com/TODO_REPO_OWNER/TODO_REPO_NAME/blob/main/docs/CONTRIBUTING.md#contributor-guide
    about: Learn about contributing to this project.
  - name: Discuss development work on the project
    url: https://groups.google.com/a/arduino.cc/g/developers
    about: Arduino Developers Mailing List
