version: "3"

includes:
  dist: ./DistTasks.yml

vars:
  PROJECT_NAME: "arduino-cli"
  DIST_DIR: "dist"
  # build vars
  COMMIT:
    sh: echo "$(git log -n 1 --format=%h)"
  TIMESTAMP:
    sh: echo "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  TIMESTAMP_SHORT:
    sh: echo "{{now | date "20060102"}}"
  TAG:
    sh: echo "`git tag --points-at=HEAD 2> /dev/null | head -n1`"
  VERSION: "{{ if .NIGHTLY }}nightly-{{ .TIMESTAMP_SHORT }}{{ else if .TAG }}{{ .TAG }}{{ else }}{{ .PACKAGE_NAME_PREFIX }}git-snapshot{{ end }}"
  LDFLAGS: >
    -ldflags
    '
    -X github.com/arduino/arduino-cli/version.versionString={{.VERSION}}
    -X github.com/arduino/arduino-cli/version.commit={{ .COMMIT }}
    -X github.com/arduino/arduino-cli/version.date={{.TIMESTAMP}}
    '

tasks: {}
